export default {
    CHANGE: 'CHANGE',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN: 'LOGIN',
    PLACE_VACCINE_ORDER: 'PLACE_VACCINE_ORDER',
    FETCH_DISTRIBUTOR_PROFILE: 'FETCH_DISTRIBUTOR_PROFILE',
    VACCINE_ORDER: 'VACCINE_ORDER',
    DISTRIBUTOR_PROFILE: 'DISTRIBUTOR_PROFILE',
    PATIENT_PROFILE: 'PATIENT_PROFILE',
    FETCH_PATIENT_PROFILE: 'FETCH_PATIENT_PROFILE',
    VACCINATE_PATIENT: 'VACCINATE_PATIENT',
    FAILED_VACCINATION: 'FAILED_VACCINATION',
    VACCINATE: 'VACCINATE',
    REGISTER_ACTION: 'REGISTER_ACTION',
    REGISTER: 'REGISTER',
    GET_INSIGHT: 'GET_INSIGHT',
    INSIGHT: 'INSIGHT'
};
